<template>
  <div class="container">
    <q-img
      :src="maerskLogo"
      no-spinner
      style="max-width: 300px; max-height: 180px"
    />
    <q-form @submit="onSubmit">
      <div class="login-form">
        <q-input
          clearable
          v-model="username"
          filled
          placeholder="Username"
          lazy-rules="ondemand"
          :rules="[(val) => (val && val.length > 0) || 'Please input username']"
        />
        <q-input
          style="margin-top: 5px"
          clearable
          v-model="password"
          filled
          placeholder="Password"
          :type="isPwd ? 'password' : 'text'"
          lazy-rules="ondemand"
          :rules="[(val) => (val && val.length > 0) || 'Please input password']"
        >
          <template v-slot:append>
            <q-icon
              :name="isPwd ? 'visibility_off' : 'visibility'"
              class="cursor-pointer"
              @click="isPwd = !isPwd"
            />
          </template>
        </q-input>
      </div>
      <q-btn class="login-button" push type="submit">
        {{ login }}
      </q-btn>
      <div class="login-link">
        <span @click="clickUserManual">
          <a href="#">{{ help }}</a>
        </span>
        <span @click="clickForgotPassword">
          <a href="#">{{ forgotPassword }}?</a>
        </span>
      </div>
    </q-form>
    <UserManual :dialogVisible="userManualVisible" @close="onCloseUserManual">
    </UserManual>
    <ForgotPwdComponent
      :dialogVisible="forgotPassordVisible"
      @confirm="onConfirmForgotPassword"
      @close="onCloseForgotPassword"
    >
    </ForgotPwdComponent>
    <div class="login-bottom">
      <q-badge transparent align="middle" color="orange" outline>
        Ver 0.1 Beta, Prod
      </q-badge>
    </div>
  </div>
</template>

<script lang="ts">
import { useRouter } from "vue-router";
import bridge from "dsbridge";
import { defineComponent, onBeforeUnmount, onMounted, ref, watch } from "vue";
import logo from "../assets/images/Maersk_Logo_RGB.svg";
import { useQuasar } from "quasar";
import {
  AndroidResponse,
  AndroidResponseStatus,
} from "../models/android.response";
import { LoginResponse } from "../models/login.response";
import md5 from "md5";
import ForgotPwdComponent from "@/components/ForgotPwdComponent.vue";
import UserManual from "@/components/UserManualComponent.vue";
import { useI18n } from "@/plugin/i18nPlugins";

const LoginView = defineComponent({
  components: {
    UserManual,
    ForgotPwdComponent,
  },
  setup() {
    const router = useRouter();
    const i18n = useI18n();
    const login = ref("");
    const help = ref("");
    const forgotPassword = ref("");
    const maerskLogo = logo;
    bridge.call("getSystemLangugae", null, (res: string) => {
      i18n.screenNm.value = "LoginView";
      i18n.locale.value = res;
      login.value = i18n.$t("login");
      help.value = i18n.$t("help");
      forgotPassword.value = i18n.$t("forgotPassword");
    });
    const username = ref("");
    const password = ref("");
    const forgotPassordVisible = ref(false);
    const userManualVisible = ref(false);
    const $q = useQuasar();
    let timer: any;
    const alertErrorMessage = (message: any) => {
      $q.notify({
        position: "center",
        color: "red-5",
        textColor: "white",
        icon: "error",
        timeout: 2000,
        message: message,
      });
    };
    onMounted(() => {
      bridge.call("checkUserUid", null, (res: string) => {
        if (res) {
          username.value = res.toUpperCase();
        }
      });
    });
    // onBeforeUnmount(() => {
    //   alert(timer);
    //   if (timer !== void 0) {
    //     clearTimeout(timer);
    //     $q.loading.hide();
    //   }
    // });
    // fix defect #3 & #4
    watch(
      username,
      () => {
        if (username.value != null) {
          username.value = username.value.toUpperCase();
        }
      },
      { immediate: true }
    );
    const showLoading = () => {
      $q.loading.show({
        message:
          'Some important <b>process</b> is in progress.<br/><span class="text-amber text-italic">Please wait...</span>',
        html: true,
      });
    };
    const onSubmit = () => {
      showLoading();
      const args = {
        // fix defect #4
        username: username.value.toUpperCase(),
        password: md5(password.value),
      };
      bridge.call("login", args, (res: string) => {
        timer == void 0;
        const androidResponse = JSON.parse(
          res
        ) as AndroidResponse<LoginResponse>;
        if (timer !== void 0) {
          clearTimeout(timer);
          $q.loading.hide();
        }
        if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
          if (androidResponse.data.autoGeneratedPassword) {
            // First time Login
            router.push({
              name: "changePassword",
              params: {
                from: "LoginView",
                username: username.value,
                password: password.value,
              },
            });
          } else {
            router.push("/home");
          }
        } else if (androidResponse.status == AndroidResponseStatus.ERROR) {
          i18n.screenNm.value = "MessageCode";
          const message = i18n.$t(androidResponse.messageCode);
          alertErrorMessage(message);
        }
      });
    };
    return {
      username,
      forgotPassword,
      login,
      help,
      maerskLogo,
      password,
      isPwd: ref(true),
      router,
      forgotPassordVisible,
      userManualVisible,
      onSubmit,
      clickUserManual() {
        userManualVisible.value = true;
      },
      clickForgotPassword() {
        forgotPassordVisible.value = true;
      },
      onCloseUserManual() {
        userManualVisible.value = false;
      },
      onCloseForgotPassword() {
        forgotPassordVisible.value = false;
      },
      onConfirmForgotPassword() {
        forgotPassordVisible.value = false;
      },
    };
  },
});
export default LoginView;
</script>
<style scoped>
.container {
  position: relative;
  width: 360px;
  padding: 15% 0 0;
  margin: auto;
  min-height: 600px;
  height: 100vh;
}
.login-form {
  width: 85%;
  margin: auto;
}
.login-link {
  width: 84%;
  margin: auto;
  display: flex;
  justify-content: space-between;
}
.login-link a {
  color: black;
}
.login-button {
  width: 85%;
  height: 50px;
  margin: 15px auto 10px;
  background-color: #00243d;
  color: white;
}
.login-bottom {
  position: absolute;
  bottom: 10px;
  left: 0;
  right: 0;
}
</style>
