<template>
  <LoadingComponent :visible="loadingStatus"> </LoadingComponent>
  <div class="wrapper">
    <div class="login-header">
      <p class="login-header-label">Login</p>
    </div>
    <q-form @submit="onSubmit" ref="myForm">
      <div class="login-form">
        <div class="field">
          <div class="input-title">
            <span class="text">{{ $t("login.account") }}</span>
          </div>
          <q-input
            class="input-field"
            input-class="text-left"
            v-model="username"
            lazy-rules
            :rules="[(val) => !!val || $t('messageCode.E91-01-0004')]"
            borderless
          >
          </q-input>
        </div>
        <div class="field">
          <div class="input-title">
            <span class="text">{{ $t("login.password") }}</span>
          </div>
          <q-input
            class="input-field"
            input-class="text-left"
            v-model="password"
            lazy-rules
            :type="isPwd ? 'password' : 'text'"
            :rules="[(val) => !!val || $t('messageCode.E91-01-0005')]"
            borderless
          >
            <template v-slot:append>
              <q-icon
                :color="isPwd ? 'gray' : 'secondary'"
                :name="isPwd ? 'visibility_off' : 'visibility'"
                class="cursor-pointer"
                @click="isPwd = !isPwd"
              />
            </template>
          </q-input>
        </div>
      </div>
      <q-btn
        no-caps
        unelevated
        class="login-button"
        type="submit"
        color="secondary"
      >
        {{ $t("login.login") }}
      </q-btn>
    </q-form>
    <div class="login-link">
      <div>
        <p class="login-link-label">
          {{ $t("login.sso_login") }}
        </p>
      </div>
      <div>
        <p class="login-link-label">
          <span @click="goFAQ">{{ $t("login.help") }} </span>
        </p>
      </div>
      <div>
        <p class="login-link-label">
          <span @click="forgotPwdVisible = true">{{
            $t("login.forgot_password")
          }}</span>
        </p>
      </div>
      <div style="margin-top: 30px">
        <q-icon name="home" color="black" size="24px" @click="goFirstPage" />
      </div>
    </div>
    <ForgotPwdComponent
      :dialogVisible="forgotPwdVisible"
      @confirm="forgotPwdVisible = false"
      @close="forgotPwdVisible = false"
      @showLoading="showLoading"
      @closeLoading="loadingStatus = false"
    ></ForgotPwdComponent>
    <PopupComponent
      :visible="popupVisible"
      :message="msg"
      :type="type"
      @close="onConfirmDialog"
      @cancel="popupVisible = false"
    ></PopupComponent>
  </div>
</template>
<script lang="ts">
import { defineComponent, onMounted, ref, watch } from "vue";
import ForgotPwdComponent from "@/components/ForgotPwdComponent.vue";
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import bridge from "dsbridge";
import md5 from "md5";
import {
  AndroidResponse,
  AndroidResponseStatus,
} from "@/models/android.response";
import { LoginResponse } from "@/models/login.response";
import { useStore } from "@/store";
import PopupComponent from "@/components/PopupComponent.vue";
import LoadingComponent from "@/components/LoadingComponent.vue";
const NewLoginView = defineComponent({
  components: {
    ForgotPwdComponent,
    PopupComponent,
    LoadingComponent,
  },
  setup() {
    const router = useRouter();
    const i18n = useI18n();
    const username = ref("");
    const password = ref("");
    const forgotPwdVisible = ref(false);
    const isPwd = ref(true);
    const store = useStore();
    const type = ref("");
    const msg = ref("");
    const popupVisible = ref(false);
    const loadingStatus = ref(false);
    const showForceLoginDialog = ref(false);
    const deviceID = ref();
    const isAutoGeneratedPassword = ref(false);
    const userID = ref();
    const myForm = ref();
    const goFirstPage = () => {
      bridge.call("goFirstPage");
    };
    onMounted(() => {
      bridge.call("checkUserUid", null, async (res: string) => {
        if (res) {
          username.value = res.toUpperCase();
        }
      });
    });
    watch(
      username,
      () => {
        if (username.value != null) {
          username.value = username.value.toUpperCase().trim();
        }
      },
      { immediate: true }
    );
    const onSubmit = () => {
      myForm.value.validate().then((success: any) => {
        if (success) {
          loadingStatus.value = true;
          const args = {
            username: username.value.toUpperCase().trim(),
            password: md5(password.value),
          };
          bridge.call("login", args, (res: string) => {
            const androidResponse = JSON.parse(
              res
            ) as AndroidResponse<LoginResponse>;
            loadingStatus.value = false;
            if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
              userID.value = androidResponse.data.userID;
              deviceID.value = androidResponse.data.deviceID;
              if (androidResponse.data.autoGeneratedPassword) {
                isAutoGeneratedPassword.value = true;
                handleFirstLogin(androidResponse.data.loginStatus);
              } else {
                isAutoGeneratedPassword.value = false;
                handleNormalLogin(androidResponse.data.loginStatus);
              }
            } else if (androidResponse.status == AndroidResponseStatus.ERROR) {
              type.value = "error";
              popupVisible.value = true;
              msg.value = i18n.t("messageCode." + androidResponse.messageCode);
            }
          });
        }
      });
    };
    const handleFirstLogin = (loginStatus: number | undefined) => {
      if (loginStatus == 3 || loginStatus == 1) {
        directToResetPassword();
      } else if (loginStatus == 2) {
        showForceLogin();
      }
    };
    const handleNormalLogin = (loginStatus: number | undefined) => {
      if (loginStatus == 3 || loginStatus == 1) {
        directToHomePage();
      } else if (loginStatus == 2) {
        showForceLogin();
      }
    };
    const showForceLogin = () => {
      showForceLoginDialog.value = true;
      type.value = "action";
      popupVisible.value = true;
      msg.value = i18n.t("login.force_login_dialog");
    };
    const forceLogin = () => {
      showForceLoginDialog.value = false;
      loadingStatus.value = true;
      const args = {
        username: username.value,
        userID: userID.value,
        autoGeneratedPassword: isAutoGeneratedPassword.value,
        password: md5(password.value),
      };
      bridge.call("forceLogin", args, (res: string) => {
        loadingStatus.value = false;
        const androidResponse = JSON.parse(
          res
        ) as AndroidResponse<LoginResponse>;
        if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
          if (isAutoGeneratedPassword.value) {
            directToResetPassword();
          } else {
            directToHomePage();
          }
        } else if (androidResponse.status == AndroidResponseStatus.ERROR) {
          const message = i18n.t("messageCode." + androidResponse.messageCode);
          type.value = "error";
          popupVisible.value = true;
          msg.value = message;
        }
      });
    };
    const directToHomePage = () => {
      store.dispatch("commonModule/setIsLogin");
      store.dispatch("commonModule/setAnimation");
      router.push("/home");
    };
    const directToResetPassword = () => {
      store.dispatch("commonModule/setIsLogin");
      router.push({
        name: "resetPwdHome",
        params: {
          from: "LoginView",
          username: username.value,
          password: password.value,
        },
      });
    };

    const goFAQ = () => {
      router.push("/faq");
    };
    const showLoading = () => {
      loadingStatus.value = true;
      forgotPwdVisible.value = false;
    };
    const onConfirmDialog = () => {
      if (showForceLoginDialog.value) {
        forceLogin();
      }
      popupVisible.value = false;
    };
    return {
      username,
      password,
      isPwd,
      forgotPwdVisible,
      onSubmit,
      goFirstPage,
      type,
      popupVisible,
      msg,
      loadingStatus,
      showForceLoginDialog,
      forceLogin,
      goFAQ,
      showLoading,
      onConfirmDialog,
      myForm,
    };
  },
});
export default NewLoginView;
</script>
<style lang="scss" scoped>
.wrapper {
  background: white;
  padding-top: 30px;
  .login-header {
    font-size: 24px;
    width: 80%;
    height: 100px;
    margin: 0 auto;
    font-variant: small-caps;
    p {
      padding: 38px 0;
    }
  }
}
.login-form {
  margin: 0 auto 10px;
  width: 80%;
  .input-label {
    color: #000000;
    text-align: left;
    margin-top: 5px;
    font-size: 12px;
  }
}
.login-button {
  margin-top: 20px;
  width: 80%;
  color: white;
  font-size: 18px;
  border-radius: 3px;
  font-variant: small-caps;
}

.login-link {
  width: 80%;
  margin: 20px auto 0;
  font-size: 14px;
  .login-link-label {
    margin: 7px 0;
  }
}
.field {
  margin: 20px 0px;
}
.q-field {
  height: 40px;
  padding: 0px;
}
</style>
