<template>
  <div class="wrapper">
    <div class="login-header">
      <p class="login-header-label">Login</p>
    </div>
    <q-form @submit="onSubmit">
      <div class="login-form">
        <div class="input-label">{{ $t("login.account") }}</div>
        <q-input
          ref="inputUsername"
          clearable
          v-model="username"
          outlined
          dense
          lazy-rules
          :rules="[(val) => !!val || $t('messageCode.E91-01-0004')]"
        />
        <div class="input-label">{{ $t("login.password") }}</div>
        <q-input
          ref="inputPassword"
          clearable
          v-model="password"
          outlined
          dense
          :type="isPwd ? 'password' : 'text'"
          lazy-rules
          :rules="[(val) => !!val || $t('messageCode.E91-01-0005')]"
        >
          <template v-slot:append>
            <q-icon
              color="black"
              :name="isPwd ? 'visibility_off' : 'visibility'"
              class="cursor-pointer"
              @click="isPwd = !isPwd"
            />
          </template>
        </q-input>
      </div>
      <q-btn
        no-caps
        unelevated
        class="login-button"
        type="submit"
        color="secondary"
      >
        {{ $t("login.login") }}
      </q-btn>
    </q-form>
    <div class="login-link">
      <div @click="userManualVisible = true">
        <p class="login-link-label">
          {{ $t("login.sso_login") }}
        </p>
      </div>
      <div @click="forgotPwdVisible = true">
        <p class="login-link-label">
          {{ $t("login.help") }}
        </p>
      </div>
      <div @click="forgotPwdVisible = true">
        <p class="login-link-label">
          {{ $t("login.forgot_password") }}
        </p>
      </div>
      <div style="margin-top: 30px">
        <q-icon name="home" color="black" size="24px" />
      </div>
    </div>
    <ForgotPwdComponent
      :dialogVisible="forgotPwdVisible"
      @confirm="forgotPwdVisible = false"
      @close="forgotPwdVisible = false"
    ></ForgotPwdComponent>
  </div>
</template>
<script lang="ts">
import { defineComponent, nextTick, onMounted, ref, watch } from "vue";
import ForgotPwdComponent from "@/components/ForgotPwdComponent.vue";
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { useQuasar } from "quasar";
import bridge from "dsbridge";
import { closeLoading, showLoading } from "@/plugin/loadingPlugins";
import md5 from "md5";
import {
  AndroidResponse,
  AndroidResponseStatus,
} from "@/models/android.response";
import { LoginResponse } from "@/models/login.response";
import { popupErrorMsg } from "@/plugin/popupPlugins";
import eyeSolid from "../assets/icon/eye-slash-solid.svg";
import { useStore } from "@/store";
const NewLoginView = defineComponent({
  components: {
    ForgotPwdComponent,
  },
  setup() {
    const router = useRouter();
    const i18n = useI18n();
    const $q = useQuasar();
    const username = ref("");
    const password = ref("");
    const inputUsername = ref();
    const inputPassword = ref();
    const forgotPwdVisible = ref(false);
    const userManualVisible = ref(false);
    const isPwd = ref(true);
    const versionNum = ref();
    const store = useStore();
    onMounted(() => {
      bridge.call("checkUserUid", null, async (res: string) => {
        if (res) {
          username.value = res.toUpperCase();
        }
        await nextTick();
        if (!username.value) {
          inputUsername.value.focus();
        } else {
          inputPassword.value.focus();
        }
      });
      bridge.call("getAppInfo", null, async (res: string) => {
        if (res) {
          versionNum.value = res;
        }
      });
    });
    watch(
      username,
      () => {
        if (username.value != null) {
          username.value = username.value.toUpperCase();
        }
      },
      { immediate: true }
    );
    const onSubmit = () => {
      showLoading($q);
      const args = {
        username: username.value.toUpperCase(),
        password: md5(password.value),
      };

      bridge.call("login", args, (res: string) => {
        const androidResponse = JSON.parse(
          res
        ) as AndroidResponse<LoginResponse>;
        closeLoading($q);
        if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
          if (androidResponse.data.autoGeneratedPassword) {
            router.push({
              name: "resetPwd",
              params: {
                from: "LoginView",
                username: username.value,
                password: password.value,
              },
            });
          } else {
            router.push("/home");
            store.dispatch("commonModule/setIsLogin");
          }
        } else if (androidResponse.status == AndroidResponseStatus.ERROR) {
          const message = i18n.t("messageCode." + androidResponse.messageCode);
          popupErrorMsg($q, message);
        }
      });
    };
    return {
      username,
      password,
      isPwd,
      forgotPwdVisible,
      userManualVisible,
      onSubmit,
      i18n,
      versionNum,
      inputUsername,
      inputPassword,
    };
  },
});
export default NewLoginView;
</script>
<style lang="scss" scoped>
.wrapper {
  background: white;
  .login-header {
    font-size: 24px;
    width: 80%;
    height: 100px;
    margin: 0 auto;
    font-variant: small-caps;
    p {
      padding: 38px 0;
    }
  }
}
.login-form {
  margin: 0 auto 10px;
  width: 80%;
  .input-label {
    color: #000000;
    text-align: left;
    margin-top: 5px;
    font-size: 12px;
  }
}
.login-button {
  width: 80%;
  color: white;
  font-size: 18px;
  border-radius: 3px;
  font-variant: small-caps;
}

.login-link {
  width: 80%;
  margin: 20px auto 0;
  font-size: 14px;
  .login-link-label {
    margin: 7px 0;
  }
}
</style>
