<template>
  <div class="wrapper">
    <div class="header">
      <div class="common-toolbar">
        <div class="common-toolbar-left">
          <img :src="arrowIcon" @click="back" />
        </div>
        <div class="common-toolbar-middle">
          {{ $t("login.change_password") }}
        </div>
        <div class="common-toolbar-right">
          <img :src="homeIcon" @click="home" />
        </div>
      </div>
    </div>
    <div class="content-card">
      <q-form @submit="onSubmit">
        <div class="input-title">{{ $t("login.current_password") }}</div>
        <q-input
          v-model="currentPwd"
          outlined
          dense
          :type="isPwd ? 'password' : 'text'"
          :placeholder="$t('login.current_password_hint')"
          lazy-rules
          :rules="[initPwdRule]"
        >
          <template v-slot:append>
            <q-icon
              :name="isPwd ? 'visibility_off' : 'visibility'"
              class="cursor-pointer"
              @click="isPwd = !isPwd"
            />
          </template>
        </q-input>
        <div class="input-title">{{ $t("login.new_password") }}</div>
        <q-input
          v-model="newPwd"
          outlined
          dense
          :type="isPwd ? 'password' : 'text'"
          :placeholder="$t('login.new_password_hint')"
          lazy-rules
          :rules="[newPwdRule]"
        >
          <template v-slot:append>
            <q-icon
              :name="isPwd ? 'visibility_off' : 'visibility'"
              class="cursor-pointer"
              @click="isPwd = !isPwd"
            />
          </template>
        </q-input>
        <div class="input-title">{{ $t("login.retype_password") }}</div>
        <q-input
          v-model="reNewPwd"
          outlined
          dense
          :type="isPwd ? 'password' : 'text'"
          :placeholder="$t('login.retype_password_hint')"
          lazy-rules
          :rules="[reNewPwdRule]"
        >
          <template v-slot:append>
            <q-icon
              :name="isPwd ? 'visibility_off' : 'visibility'"
              class="cursor-pointer"
              @click="isPwd = !isPwd"
            />
          </template>
        </q-input>
        <div class="button-bottom">
          <q-btn
            no-caps
            outline
            text-color="grey"
            :label="$t('common.cancel')"
            @click="cancel"
          />
          <q-btn
            no-caps
            unelevated
            color="secondary"
            type="submit"
            :label="$t('common.save')"
          />
        </div>
      </q-form>
    </div>
  </div>
</template>
<script lang="ts">
import {
  AndroidResponse,
  AndroidResponseStatus,
} from "@/models/android.response";
import { LogoutResponse, UpdateLoginUser } from "@/models/login.response";
import bridge from "dsbridge";
import { useQuasar } from "quasar";
import { defineComponent, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import md5 from "md5";
import { popupErrorMsg, popupSuccessMsg } from "@/plugin/popupPlugins";
import { closeLoading, showLoading } from "@/plugin/loadingPlugins";
import { useI18n } from "vue-i18n";
import homeImg from "../assets/images/home.svg";
import arrowImg from "../assets/images/arrow.svg";
const ResetPwdView = defineComponent({
  setup() {
    const route = useRoute();
    const router = useRouter();
    const $q = useQuasar();
    const i18n = useI18n();
    const currentPwd = ref("");
    const newPwd = ref("");
    const reNewPwd = ref("");
    const username = ref("");
    const initPwd = ref();
    const from = ref("");
    const isPwd = ref(true);
    const homeIcon = homeImg;
    const arrowIcon = arrowImg;
    onMounted(() => {
      from.value = route.params.from as string;
      username.value = route.params.username as string;
      initPwd.value = route.params.password as string;
    });
    const onSubmit = () => {
      showLoading($q);
      const args: UpdateLoginUser = {
        username: username.value,
        password: md5(newPwd.value),
        autoGeneratedPassword: false,
      };
      bridge.call("resetPassword", args, (res: string) => {
        closeLoading($q);
        const androidResponse = JSON.parse(res) as AndroidResponse<unknown>;
        if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
          const message = i18n.t("messageCode.E93-02-0001");
          if (from.value == "LoginView") {
            router.push("/home");
          } else if (from.value == "SettingView") {
            router.push("/setting");
          }
          popupSuccessMsg($q, message);
        } else if (androidResponse.status == AndroidResponseStatus.ERROR) {
          const message = i18n.t("messageCode." + androidResponse.messageCode);
          popupErrorMsg($q, message);
        }
      });
    };
    const initPwdRule = (val: string) => {
      return new Promise((resolve) => {
        if (!val) {
          const message = i18n.t("messageCode.E93-02-0005");
          resolve(message);
        } else {
          if (from.value === "SettingView") {
            if (md5(currentPwd.value) != initPwd.value) {
              const message = i18n.t("messageCode.E93-02-0003");
              resolve(message);
            } else {
              resolve(true);
            }
          } else {
            if (currentPwd.value != initPwd.value) {
              const message = i18n.t("messageCode.E93-02-0003");
              resolve(message);
            } else {
              resolve(true);
            }
          }
        }
      });
    };
    const newPwdRule = (val: string) => {
      return new Promise((resolve) => {
        const reg = /[A-Z]+/g;
        const reg2 = /[0-9]+/g;
        if (!val) {
          const message = i18n.t("messageCode.E93-02-0006");
          resolve(message);
        } else {
          if (newPwd.value.length < 8) {
            const message = i18n.t("messageCode.E93-02-0004");
            resolve(message);
          } else {
            if (!reg.test(newPwd.value)) {
              const message = i18n.t("messageCode.E93-02-0004");
              resolve(message);
            } else if (!reg2.test(newPwd.value)) {
              const message = i18n.t("messageCode.E93-02-0004");
              resolve(message);
            } else {
              resolve(true);
            }
          }
        }
      });
    };
    const reNewPwdRule = (val: string) => {
      return new Promise((resolve) => {
        if (!val) {
          const message = i18n.t("messageCode.E93-02-0007");
          resolve(message);
        } else {
          if (newPwd.value != reNewPwd.value) {
            const message = i18n.t("messageCode.E93-02-0002");
            resolve(message);
          } else {
            resolve(true);
          }
        }
      });
    };
    const cancel = () => {
      if (from.value == "LoginView") {
        bridge.call("logout", null, (data: string) => {
          const androidResponse = JSON.parse(
            data
          ) as AndroidResponse<LogoutResponse>;
          if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
            const message = i18n.t("messageCode.E93-06-0001");
            router.push("/");
            popupSuccessMsg($q, message);
          }
        });
      } else if (from.value == "SettingView") {
        router.push("/setting");
      }
    };
    const back = () => {
      if (from.value == "LoginView") {
        cancel();
      } else if (from.value == "SettingView") {
        router.push("/setting");
      }
    };
    return {
      isPwd,
      onSubmit,
      cancel,
      back,
      currentPwd,
      newPwd,
      reNewPwd,
      initPwdRule,
      newPwdRule,
      reNewPwdRule,
      homeIcon,
      arrowIcon,
    };
  },
});
export default ResetPwdView;
</script>
<style lang="scss" scoped>
.content-card {
  padding: 0 20px;
  text-align: left;
  .input-title {
    margin: 5px 0;
  }
  .q-input {
    margin-bottom: 0;
  }
}
.button-bottom {
  position: fixed;
  bottom: 10px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 90%;
  .q-btn {
    margin-top: 10px;
    width: 100%;
  }
}
</style>
