<template>
  <div class="wrapper">
    <div class="header">
      <q-item clickable>
        <q-item-section avatar @click="back">
          <q-icon name="arrow_back" />
        </q-item-section>
        <q-item-section>
          <span class="header-title">Change Password</span></q-item-section
        >
      </q-item>
    </div>
    <q-separator />
    <q-card class="content-card">
      <q-form @submit="onSubmit">
        <div class="content-input">
          <q-input
            v-model="currentPwd"
            filled
            :type="isPwd ? 'password' : 'text'"
            placeholder="Current Password"
            lazy-rules
            :rules="[initPwdRule]"
          >
            <template v-slot:append>
              <q-icon
                :name="isPwd ? 'visibility_off' : 'visibility'"
                class="cursor-pointer"
                @click="isPwd = !isPwd"
              />
            </template>
          </q-input>
          <q-input
            v-model="newPwd"
            filled
            :type="isPwd ? 'password' : 'text'"
            placeholder="New Password"
            lazy-rules
            :rules="[newPwdRule]"
          >
            <template v-slot:append>
              <q-icon
                :name="isPwd ? 'visibility_off' : 'visibility'"
                class="cursor-pointer"
                @click="isPwd = !isPwd"
              />
            </template>
          </q-input>
          <q-input
            v-model="reNewPwd"
            filled
            :type="isPwd ? 'password' : 'text'"
            placeholder="Retype New Password"
            lazy-rules
            :rules="[reNewPwdRule]"
          >
            <template v-slot:append>
              <q-icon
                :name="isPwd ? 'visibility_off' : 'visibility'"
                class="cursor-pointer"
                @click="isPwd = !isPwd"
              />
            </template>
          </q-input>
        </div>
        <div class="bottom">
          <q-btn
            no-caps
            style="width: 48%"
            flat
            push
            label="Cancel"
            @click="cancel"
          />
          <q-separator vertical inset color="white" />
          <q-btn
            no-caps
            style="width: 52%"
            flat
            type="submit"
            push
            label="Save"
          />
        </div>
      </q-form>
    </q-card>
  </div>
</template>
<script lang="ts">
import {
  AndroidResponse,
  AndroidResponseStatus,
} from "@/models/android.response";
import { LogoutResponse, UpdateLoginUser } from "@/models/login.response";
import bridge from "dsbridge";
import { useQuasar } from "quasar";
import { defineComponent, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import md5 from "md5";
import { popupErrorMsg, popupSuccessMsg } from "@/plugin/popupPlugins";
import { useI18n } from "@/plugin/i18nPlugins";
import { closeLoading, showLoading } from "@/plugin/loadingPlugins";

const ResetPwdView = defineComponent({
  setup() {
    const route = useRoute();
    const router = useRouter();
    const $q = useQuasar();
    const i18n = useI18n();
    const currentPwd = ref("");
    const newPwd = ref("");
    const reNewPwd = ref("");
    const username = ref("");
    const initPwd = ref();
    const from = ref("");
    const isPwd = ref(true);
    onMounted(() => {
      from.value = route.params.from as string;
      username.value = route.params.username as string;
      initPwd.value = route.params.password as string;
      bridge.call("getSystemLanguage", null, (res: string) => {
        i18n.locale.value = res;
      });
    });
    const onSubmit = () => {
      showLoading($q);
      const args: UpdateLoginUser = {
        username: username.value,
        password: md5(newPwd.value),
        autoGeneratedPassword: false,
      };
      bridge.call("resetPassword", args, (res: string) => {
        closeLoading($q);
        const androidResponse = JSON.parse(res) as AndroidResponse<unknown>;
        if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
          const message = i18n.$t("E00-01-0010");
          if (from.value == "LoginView") {
            router.push("/home");
          } else if (from.value == "SettingView") {
            router.push("/setting");
          }
          popupSuccessMsg($q, message);
        } else if (androidResponse.status == AndroidResponseStatus.ERROR) {
          const message = i18n.$t(androidResponse.messageCode);
          popupErrorMsg($q, message);
        }
      });
    };
    const initPwdRule = (val: string) => {
      i18n.category.value = "MessageCode";
      return new Promise((resolve) => {
        if (!val) {
          const message = i18n.$t("E00-01-0015");
          resolve(message);
        } else {
          if (from.value === "SettingView") {
            if (md5(currentPwd.value) != initPwd.value) {
              const message = i18n.$t("E00-01-0012");
              resolve(message);
            } else {
              resolve(true);
            }
          } else {
            if (currentPwd.value != initPwd.value) {
              const message = i18n.$t("E00-01-0012");
              resolve(message);
            } else {
              resolve(true);
            }
          }
        }
      });
    };
    const newPwdRule = (val: string) => {
      i18n.category.value = "MessageCode";
      return new Promise((resolve) => {
        const reg = /[A-Z]+/g;
        const reg2 = /[0-9]+/g;
        if (!val) {
          const message = i18n.$t("E00-01-0016");
          resolve(message);
        } else {
          if (newPwd.value.length < 8) {
            const message = i18n.$t("E00-01-0013");
            resolve(message);
          } else {
            if (!reg.test(newPwd.value)) {
              const message = i18n.$t("E00-01-0013");
              resolve(message);
            } else if (!reg2.test(newPwd.value)) {
              const message = i18n.$t("E00-01-0013");
              resolve(message);
            } else {
              resolve(true);
            }
          }
        }
      });
    };
    const reNewPwdRule = (val: string) => {
      i18n.category.value = "MessageCode";
      return new Promise((resolve) => {
        if (!val) {
          const message = i18n.$t("E00-01-0017");
          resolve(message);
        } else {
          if (newPwd.value != reNewPwd.value) {
            const message = i18n.$t("E00-01-0011");
            resolve(message);
          } else {
            resolve(true);
          }
        }
      });
    };
    const cancel = () => {
      if (from.value == "LoginView") {
        bridge.call("logout", null, (data: string) => {
          const androidResponse = JSON.parse(
            data
          ) as AndroidResponse<LogoutResponse>;
          if (androidResponse.status == AndroidResponseStatus.SUCCESS) {
            const message = i18n.$t("E00-01-0014");
            router.push("/");
            popupSuccessMsg($q, message);
          }
        });
      } else if (from.value == "SettingView") {
        router.push("/setting");
      }
    };
    const back = () => {
      if (from.value == "LoginView") {
        cancel();
      } else if (from.value == "SettingView") {
        router.push("/setting");
      }
    };
    return {
      isPwd,
      onSubmit,
      cancel,
      back,
      currentPwd,
      newPwd,
      reNewPwd,
      initPwdRule,
      newPwdRule,
      reNewPwdRule,
    };
  },
});
export default ResetPwdView;
</script>
<style lang="scss" scoped>
.wrapper {
  height: 100vh;
  display: flex;
  flex-flow: column;
  background-color: #dbdbdb;
}
.header {
  padding-top: 1px;
  padding-bottom: 1px;
  width: 100%;
  background-color: white;
  color: gray;
}
.header-title {
  font-size: 21px;
  color: black;
  margin-left: -10%;
}
.content-card {
  padding-top: 20px;
  padding-bottom: 5px;
}
.content-input {
  width: 95%;
  margin: 0 auto;
}
.bottom {
  position: fixed;
  bottom: 0px;
  display: flex;
  background: #42b0d5;
  color: white;
  width: 100%;
  height: 50px;
}
</style>
