name: Build

# env:
#   GITHUB_USER_REF: ${{ secrets.GH_PACKAGE_REPO_USERNAME }}
#   GITHUB_TOKEN_REF: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
#   REGISTRY: ghcr.io
#   ORGANIZATION: maersk-global
#   REPOSITORY: ${{ github.repository }}
#   IMAGE_NAME: snd-warehousing-support-web
#   IMAGE_VERSION: 1.0.1-SNAPSHOT

on:
  push:
    branches: [develop]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install and Build
        run: |
          npm install
          npm run build

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
      #     labels: ${{ steps.meta.outputs.labels }}
