export class LoginResponse {
  token: string | undefined;
  deviceID: string | undefined;
  loginStatus: number | undefined;
  autoGeneratedPassword: boolean | undefined;
  userID: string | undefined;
}

export class LoginUser {
  username: string | undefined;
  password: string | undefined;
}

export class UpdateLoginUser {
  username: string | undefined;
  password: string | undefined;
  autoGeneratedPassword: boolean | undefined;
}

export class LogoutResponse {
  uid: string | undefined;
  isSuccess: boolean | undefined;
}
